"""Step 8 (optional): Write generated tests to disk and push a git commit."""

from __future__ import annotations

import os
import subprocess

from pr_test_automator._logging import get_logger
from pr_test_automator.config import PRTestConfig
from pr_test_automator.models import GeneratedTest, PRInfo
from pr_test_automator.utils.exceptions import TestPusherError

logger = get_logger(__name__)

_GIT_TIMEOUT = 60


class TestPusher:
    """Writes test files to the local repo and pushes them to the PR branch."""

    def __init__(self, config: PRTestConfig) -> None:
        self._config = config

    def push(self, tests: list[GeneratedTest], pr_info: PRInfo) -> str:
        """Write tests, commit, push; return the new commit SHA."""
        written = self._write_files(tests)
        if not written:
            logger.info("no test files to push")
            return ""

        branch = self._config.pr_branch or pr_info.head_branch
        self._git_checkout(branch)
        self._git_add(written)
        sha = self._git_commit(len(written))
        self._git_push(branch)

        logger.info(
            "pushed test commit",
            extra={"files": len(written), "branch": branch, "sha": sha},
        )
        return sha

    def _write_files(self, tests: list[GeneratedTest]) -> list[str]:
        written: list[str] = []
        for gen in tests:
            dest = os.path.join(self._config.repo_path, gen.test_file_path)
            os.makedirs(os.path.dirname(dest), exist_ok=True)
            with open(dest, "w", encoding="utf-8") as fh:
                fh.write(gen.content)
            written.append(gen.test_file_path)
            logger.info("test file written", extra={"path": gen.test_file_path})
        return written

    def _git_checkout(self, branch: str) -> None:
        self._run(["git", "checkout", branch])

    def _git_add(self, paths: list[str]) -> None:
        self._run(["git", "add", "--", *paths])

    def _git_commit(self, file_count: int) -> str:
        message = (
            f"chore: add auto-generated tests for {file_count} file(s)\n\n"
            "Generated by pr-test-automator using Claude."
        )
        self._run(
            [
                "git",
                "-c",
                f"user.name={self._config.bot_name}",
                "-c",
                f"user.email={self._config.bot_email}",
                "commit",
                "-m",
                message,
            ]
        )
        return self._run(["git", "rev-parse", "HEAD"], capture=True).strip()

    def _git_push(self, branch: str) -> None:
        self._run(["git", "push", "origin", f"HEAD:{branch}"])

    def _run(self, cmd: list[str], capture: bool = False) -> str:
        try:
            proc = subprocess.run(
                cmd,
                cwd=self._config.repo_path,
                capture_output=capture,
                text=True,
                timeout=_GIT_TIMEOUT,
                check=True,
            )
            return proc.stdout if capture else ""
        except subprocess.CalledProcessError as exc:
            raise TestPusherError(
                f"git command failed: {' '.join(cmd)}\n{exc.stderr}"
            ) from exc
        except subprocess.TimeoutExpired as exc:
            raise TestPusherError(
                f"git command timed out: {' '.join(cmd)}"
            ) from exc
