"""Configuration dataclass for the PR Test Automator pipeline."""

from __future__ import annotations

from dataclasses import dataclass, field

GITHUB_API_BASE = "https://api.github.com"
DEFAULT_MODEL = "claude-sonnet-4-5"
DEFAULT_MAX_FIX_RETRIES = 3
DEFAULT_TIMEOUT = 30
DEFAULT_TEST_DIRS: tuple[str, ...] = ("tests", "test")
DEFAULT_BOT_NAME = "pr-test-automator[bot]"
DEFAULT_BOT_EMAIL = "pr-test-automator[bot]@users.noreply.github.com"
DEFAULT_COMMENT_FOOTER = (
    "*Generated by [pr-test-automator]"
    "(https://github.com/gautamkumar-asurint/pr-test-automator) powered by Claude.*"
)


@dataclass
class PRTestConfig:
    """Settings needed to run the full PR test automation pipeline.

    Required:
        github_token:    GitHub PAT or GITHUB_TOKEN with ``contents:read`` plus
                         ``pull-requests:write`` (and ``contents:write`` if
                         ``push_test_commit`` is enabled).
        claude_api_key:  Anthropic API key for test generation and fixing.
        repo:            GitHub repo as ``"owner/repo"``.
        repo_path:       Absolute local path to the checked-out repository.

    Optional:
        pr_branch:           PR head branch (used when pushing tests). Derived
                             automatically from the PR if omitted.
        max_fix_retries:     How many times to re-prompt Claude after pytest
                             failures.
        push_test_commit:    When True, generated tests are committed and pushed
                             back to the PR branch.
        model:               Anthropic model ID.
        github_api_base:     Override for GitHub Enterprise Server.
        test_dirs:           Directories to search for existing tests, in
                             priority order. The first entry is also used as
                             the destination for newly generated test files.
        timeout:             HTTP request timeout in seconds.
        bot_name:            Git author name used when pushing test commits.
        bot_email:           Git author email used when pushing test commits.
        comment_footer:      Markdown footer appended to PR comments.
        source_root:         Optional repo-relative path used to limit which
                             files are analyzed (e.g. ``"app/src"``). When set,
                             only Python files under this path are processed.
                             ``None`` analyzes every Python file in the diff.
        test_file_extra_dirs: Additional candidate directories appended to
                             ``test_dirs`` at runtime (lower priority).
    """

    github_token: str
    claude_api_key: str
    repo: str
    repo_path: str
    pr_branch: str | None = None
    max_fix_retries: int = DEFAULT_MAX_FIX_RETRIES
    push_test_commit: bool = False
    model: str = DEFAULT_MODEL
    github_api_base: str = GITHUB_API_BASE
    test_dirs: list[str] = field(
        default_factory=lambda: list(DEFAULT_TEST_DIRS),
    )
    timeout: int = DEFAULT_TIMEOUT
    bot_name: str = DEFAULT_BOT_NAME
    bot_email: str = DEFAULT_BOT_EMAIL
    comment_footer: str = DEFAULT_COMMENT_FOOTER
    source_root: str | None = None
    test_file_extra_dirs: list[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        if "/" not in self.repo:
            raise ValueError(
                f"repo must be in 'owner/repo' format, got: {self.repo!r}"
            )
        if not self.github_token:
            raise ValueError("github_token must not be empty")
        if not self.claude_api_key:
            raise ValueError("claude_api_key must not be empty")
        if self.max_fix_retries < 0:
            raise ValueError("max_fix_retries must be >= 0")

    @property
    def owner(self) -> str:
        return self.repo.split("/", 1)[0]

    @property
    def repo_name(self) -> str:
        return self.repo.split("/", 1)[1]

    @property
    def github_headers(self) -> dict[str, str]:
        return {
            "Authorization": f"Bearer {self.github_token}",
            "Accept": "application/vnd.github.v3+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }

    @property
    def all_test_dirs(self) -> list[str]:
        """Effective list of test directories to search (priority order)."""
        return [*self.test_dirs, *self.test_file_extra_dirs]
